# Generated by Django 5.1 on 2024-08-24 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='image',
        ),
    ]
