# Generated by Django 5.1 on 2024-08-21 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_notes_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
